name: orical_imeitag
description: Tamper-evident on-screen IMEI / device-info barcode display with selectable capture path.
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  barcode_widget: ^2.0.4
  flutter_secure_storage: ^9.2.2
  screen_brightness: ^1.0.1
  crypto: ^3.0.3
  intl: ^0.19.0
  google_mlkit_text_recognition: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
